name: Health Check GitHub action

on:
     schedule:
       - cron: '34 16 * * *'


jobs:
    Healthcheck:
        runs-on: ubuntu-20.04
        steps:
            - name: Check the deployed service URL
              uses: jtalk/url-health-check-action@v3
              with:
                # Check the following URLs one by one sequentially
                # Seems like the free tier in render is slow to respond to first queries
                # and this request can time out if the vm is inactive
                url: https://rendered-pipe.onrender.com/